version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_storage:/qdrant/storage
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    # No healthcheck to keep things simple/portable
  ingester:
    build: ingester
    container_name: ingester
    depends_on:
      qdrant:
        condition: service_started
      dynamodb:
        condition: service_started
    environment:
      QDRANT_URL: http://qdrant:6333
      COLLECTION_NAME: documents
      OPENAI_API_KEY: $OPENAI_API_KEY
    volumes:
      - ./ingester/data:/data:ro
    # This container is expected to ingest once and exit.
    restart: "no"
  chatbot:
    build: app
    container_name: chatbot
    depends_on:
      qdrant:
        condition: service_started
      dynamodb:
        condition: service_started
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
    ports:
      - "8501:8501"
    restart: unless-stopped

#  chatbot:
#    build: ./chatbot
#    container_name: chatbot
#    depends_on:
#      qdrant:
#        condition: service_healthy
#    environment:
#      QDRANT_URL: http://qdrant:6333
#      COLLECTION_NAME: documents
#      # QDRANT_API_KEY: ""   # uncomment if you secure Qdrant
#    ports:
#      - "8501:8501"
#    restart: unless-stopped

volumes:
  qdrant_storage:
  dynamodb_data:
